#pragma config(Sensor, in1,    Left,           sensorLineFollower)
#pragma config(Sensor, in2,    Center,         sensorLineFollower)
#pragma config(Sensor, in3,    Right,          sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)


#include "Vex_Competition_Includes.c"


int leftMin = 4095;
int leftMax = 0;

int rightMin = 4095;
int rightMax = 0;

int centerMin = 4095;
int centerMax = 0;




task Calibrator(){
	while(true){
		if(SensorValue[Left] > leftMax)
			leftMax = SensorValue[Left];
		if(SensorValue[Left] < leftMin)
			leftMin = SensorValue[Left];

		if(SensorValue[Center] > centerMax)
			centerMax = SensorValue[Center];
		if(SensorValue[Center] < centerMin)
			centerMin = SensorValue[Center];

		if(SensorValue[Right] > rightMax)
			rightMax = SensorValue[Right];
		if(SensorValue[Right] < rightMin)
			rightMin = SensorValue[Right];
	}
}

void pre_auton()
{
	startTask(Calibrator);

}
int getSensorPercent(int value,int min, int max){

	int return_val= (100*(value-min))/(max-min);
	if(return_val<0)
		return 0;
	if(return_val>100)
		return 100;
	return return_val;

}

task autonomous()
{
	stopTask(Calibrator);

	int leftValue = getSensorPercent(SensorValue[Left],leftMin,leftMax);//0 - 100% of possible values
	int rightValue = getSensorPercent(SensorValue[Right],rightMin,rightMax);//0 - 100% of possible values
	int centerValue = getSensorPercent(SensorValue[Center],centerMin,centerMax);//0 - 100% of possible values

}

task usercontrol()
{


	while (true)
	{

	}
}
